### ISSUE TITLE
AttributeError: 'module' object has no attribute 'paint_bc' in ubuntu 

### ISSUE THREAD

**Issue by cn0xroot** [drmpeg/gr-paint#10]
```
Executing: /usr/bin/python -u /home/init3/sdr/gr-paint/apps/paint_tx.py

linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

-- Detected Device: B210
-- Operating over USB 3.
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Performing CODEC loopback test... pass
-- Asking for clock rate 8.000000 MHz... 
-- Actually got clock rate 8.000000 MHz.
-- Performing timer loopback test... pass
-- Performing timer loopback test... pass
Using Volk machine: avx2_64_mmx_orc
Traceback (most recent call last):
  File "/home/init3/sdr/gr-paint/apps/paint_tx.py", line 171, in <module>
    main()
  File "/home/init3/sdr/gr-paint/apps/paint_tx.py", line 159, in main
    tb = top_block_cls()
  File "/home/init3/sdr/gr-paint/apps/paint_tx.py", line 114, in __init__
    self.paint_paint_bc_0 = paint.paint_bc(1920, 8, paint.EQUALIZATION_OFF, paint.INTERNAL, 1)
AttributeError: 'module' object has no attribute 'paint_bc'

>>> Done
```

**Comment by jewirth** [comment]
I had the same issue. How did you fix it?

**Comment by drmpeg** [comment]
It's usually an install issue. For OOT modules, you have to match the install directory to where you installed GNU Radio. For example, if you installed GNU Radio from a distro package, it would be in /usr. Then you'd have to build gr-paint with:

cmake -DCMAKE_INSTALL_PREFIX=/usr ../
